# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-25 06:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20180925_1155'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gallery',
            new_name='Photo',
        ),
    ]
