# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-24 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='logo',
            field=models.ImageField(default='user/infortx.png', upload_to='logo/%Y/%m/%d', verbose_name='LOGO'),
        ),
    ]
