# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-24 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_person_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logo/%Y/%m/%d', verbose_name='图片')),
            ],
        ),
    ]
