# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-24 07:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20180924_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sendimage',
            old_name='logo',
            new_name='head',
        ),
    ]
