# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-24 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20180924_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='head',
            field=models.ImageField(default='logo/2018/09/24/infortx.png', upload_to='head/%Y/%m/%d', verbose_name='head'),
        ),
        migrations.AlterField(
            model_name='sendimage',
            name='head',
            field=models.ImageField(upload_to='imgs/%Y/%m/%d', verbose_name='图片'),
        ),
    ]
