# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-27 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('take_goods_name', models.CharField(max_length=20, verbose_name='收货人姓名')),
                ('mobile', models.CharField(max_length=12, verbose_name='收货人电话')),
                ('province_id', models.CharField(max_length=100, verbose_name='省id')),
                ('city_id', models.CharField(max_length=100, verbose_name='市id')),
                ('district_id', models.CharField(max_length=100, verbose_name='区id')),
                ('row_id', models.CharField(max_length=100, verbose_name='街道id')),
                ('describe', models.CharField(max_length=255, verbose_name='详细描述')),
                ('is_default_address', models.BooleanField(default=False, verbose_name='是否默认地址')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Person', verbose_name='用户id')),
            ],
            options={
                'verbose_name': '收货地址管理',
                'verbose_name_plural': '收货地址管理',
            },
        ),
    ]
