# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-28 01:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('goods', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('order_num', models.CharField(max_length=20, verbose_name='订单编号')),
                ('order_price', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='订单金额')),
                ('take_goods_name', models.CharField(max_length=20, verbose_name='收货人姓名')),
                ('mobile', models.CharField(max_length=12, verbose_name='收货人电话')),
                ('address', models.CharField(max_length=200, verbose_name='收货人地址')),
                ('order_status', models.SmallIntegerField(choices=[(0, '待发货'), (1, '待收货'), (2, '待评价'), (3, '退换货'), (4, '已完成')], verbose_name='订单状态')),
                ('transport_price', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='运费')),
                ('actual_amount', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='实付金额')),
            ],
            options={
                'verbose_name': '订单管理',
                'verbose_name_plural': '订单管理',
            },
        ),
        migrations.CreateModel(
            name='OrderShops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(verbose_name='商品数量')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='商品价格')),
                ('goods_sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsSKU', verbose_name='商品id')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('pay_name', models.CharField(max_length=20, verbose_name='支付名称')),
                ('img', models.ImageField(upload_to='pay/%Y/%m/%d', verbose_name='图片')),
            ],
            options={
                'verbose_name': '支付方式',
                'verbose_name_plural': '支付方式',
            },
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=20, verbose_name='运输方式名称')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='价格')),
            ],
            options={
                'verbose_name': '运输方式',
                'verbose_name_plural': '运输方式',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='pay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Pay', verbose_name='付款方式'),
        ),
        migrations.AddField(
            model_name='order',
            name='transport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Transport', verbose_name='运输方式'),
        ),
        migrations.AddField(
            model_name='order',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Person', verbose_name='用户id'),
        ),
    ]
