# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-28 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20180928_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='district_id',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='区id'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='row_id',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='街道id'),
        ),
    ]
