# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-29 01:09
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20180928_1921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddress',
            old_name='district_id',
            new_name='harea',
        ),
        migrations.RenameField(
            model_name='useraddress',
            old_name='province_id',
            new_name='hcity',
        ),
        migrations.RenameField(
            model_name='useraddress',
            old_name='city_id',
            new_name='hproper',
        ),
        migrations.RenameField(
            model_name='useraddress',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='mobile',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^1[3-9]\\d{9}$', '手机格式错误')], verbose_name='收货人电话'),
        ),
    ]
